server:
  port: 9767
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master # 指明远程仓库的分支
      profile: dev  # dev开发环境配置文件 test测试环境  pro正式环境
      #     uri: http://localhost:8888/  #指明配置服务中心的网址
      discovery:
        enabled: true # 是从配置中心读取文件。
        service-id: config-server # 配置中心的servieId，即服务名。
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 将服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

