server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ciziyong/hello/    # 配置git仓库地址  https://github.com/ciziyong/hello
          search-paths: respo   # 配置仓库路径
          username:     # 访问git仓库的用户名
          password:     # 访问git仓库的用户密码
      label: master      # 配置仓库的分支
#将服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/